from . import res_users
from . import partner
from . import coop
from . import invoice
from . import coop_membership
from . import product
from . import activity_area
from . import loan_issue
from . import mail_template
from . import res_company
